# Generated by Django 3.2.4 on 2021-06-23 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ResBuild', '0003_courses_coursetypes_pors_projects_skills_skilltypes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursetypes',
            old_name='courseType',
            new_name='CourseType',
        ),
        migrations.RenameField(
            model_name='pors',
            old_name='PoRDesc',
            new_name='PorDesc',
        ),
        migrations.RenameField(
            model_name='pors',
            old_name='porName',
            new_name='PorName',
        ),
        migrations.RenameField(
            model_name='pors',
            old_name='PORPeriod',
            new_name='PorPeriod',
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='PrjectDesc',
            new_name='ProjectDesc',
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='projectPeriod',
            new_name='ProjectPeriod',
        ),
        migrations.RenameField(
            model_name='skills',
            old_name='skillName',
            new_name='SkillName',
        ),
        migrations.RenameField(
            model_name='skills',
            old_name='skillType',
            new_name='SkillType',
        ),
        migrations.RenameField(
            model_name='skilltypes',
            old_name='skillType',
            new_name='SkillType',
        ),
    ]
